### ISSUE TITLE
Создание user-interface для отладочной программы

### ISSUE THREAD

**Issue by fullofcriticism** [citec-spbu/Debugger-Dynamics-VR#2]

**Comment by MrArliton** [comment]
Интерфейс в целом готов.
Есть костыльная реализация взаимодействия через файловую систему.
Нужно реализовывать нормальную используя winapi - Ждём реализацию issue с этой задачей.

**Comment by fullofcriticism** [comment]
Ветка по задаче #7

**Comment by fullofcriticism** [comment]
Добавлена кнопка подключения/отключения из задачи #12
